export enum educationActionTypes {
  SET_QUALIFICATION = 'SET_QUALIFICATION',
  SET_UNIVERSITY = 'SET_UNIVERSITY',
  SET_STARTDATE = 'SET_STARTDATE',
  SET_ENDDATE = 'SET_ENDDATE',
  SET_LEARNINGS = 'SET_LEARNINGS',
}